Vereinheitlichung der Einheiten
dominikth13/autonomous_on_demand_systems pull request #7
Opened 2023-11-14 18:50 UTC by vicky-di-zhang

The unit of time is second 
The unit of location is meter now

2023-11-14 18:52 UTC, vicky-di-zhang commented
![](https://github.trello.services/images/mini-trello-icon.png) [Vereinheitlichung der im Algorithmus verwendeten Einheiten](https://trello.com/c/jUsLo6we/7-vereinheitlichung-der-im-algorithmus-verwendeten-einheiten)

2023-11-15 14:19 UTC, dominikth13 requested changes
Schon mal guter Anfang. Aber die Kommentare bitte noch umsetzen

2023-11-15 14:19 UTC, dominikth13 commented on code/state_value_table.py
> +    TimeSeries(Time(3, 0, 0), Time(14, 0, 0), 5),
Bei der 5 wird ja vermutlich noch Minuten verwendet. Da bitte auch in Sekunden

2023-11-15 14:19 UTC, dominikth13 commented on code/time_interval.py
> +        self.second = second
Hmm, ich hatte mir das etwas anders vorgestellt. Und zwar wird Zeit in der Informatik immer als eine Zahl angegeben. Dabei wird der Startpunkt der Zeit festgelegt und von dort wird einfach angefangen zu zählen. 00:00 Uhr wäre in unserem Beispiel die Zahl 0. 00:01 Uhr wäre die 60, 01:00 Uhr wäre die 3600 und 13:29 Uhr die 48540. Wenn wir das als ganze Zahl speichern, ist auch das Umrechnen deutlich leichter.

2023-11-15 14:19 UTC, dominikth13 commented on code/time_interval.py
> +        self.second = second
Du müsstest hier also alle Variablen löschen und nur noch die Variable `total_seconds` behalten. Der Trick bei der Sache: Bei den Funktionen und Methoden musst du die Paramter gar nicht ändern. Man kann hier vortäuschen, mit einer richtigen Zeitinterpretation zu abeiten, obwohl im Hintergrund nur eine ganze Zahl, die "Totalsekunde", steht.

2023-11-15 14:19 UTC, dominikth13 commented on code/time_interval.py
> +    def of_total_minutes(minutes: float) -> Time:
Dementsprechend bei allein Methoden der `Time` Klasse die Berechnung der Rückgabewerte verändern.

2023-11-15 20:28 UTC, closed without merging